In [1]:
import torchaudio
from speechbrain.pretrained import EncoderClassifier
# hparams() means hyper-parameters?
language_clf = EncoderClassifier.from_hparams(
    source="TalTechNLP/voxlingua107-epaca-tdnn",
    savedir="tmp",
)
# Download a Thai language sample from Omniglot and convert it to suitable form
signal = language_clf.load_audio("https://omniglot.com/soundfiles/udhr/udhr_th.mp3")
type(signal)

torch.Tensor

In [10]:
signal

tensor([0., 0., 0.,  ..., 0., 0., 0.])

In [11]:
pred = language_clf.classify_batch(signal)
type(pred)

tuple

In [12]:
len(pred)

4

In [13]:
for x in pred:
    print(type(x))

<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'list'>


In [14]:
pred[-1]

['th']

In [15]:
pred

(tensor([[0.3233, 0.3781, 0.3702, 0.3957, 0.4054, 0.3674, 0.3713, 0.3625, 0.3535,
          0.3686, 0.3917, 0.3999, 0.3873, 0.3989, 0.3973, 0.3614, 0.4387, 0.4022,
          0.4131, 0.3912, 0.4198, 0.3893, 0.3790, 0.3792, 0.3701, 0.4023, 0.4283,
          0.4124, 0.3587, 0.3723, 0.3339, 0.3863, 0.3875, 0.3888, 0.3902, 0.3966,
          0.3952, 0.4090, 0.3831, 0.3856, 0.3015, 0.4217, 0.4006, 0.3678, 0.3982,
          0.3768, 0.4323, 0.3833, 0.3640, 0.4731, 0.3553, 0.4179, 0.3674, 0.3799,
          0.3840, 0.6093, 0.3735, 0.3913, 0.3794, 0.4042, 0.3811, 0.3629, 0.4219,
          0.3742, 0.4428, 0.3267, 0.3888, 0.3893, 0.4132, 0.4321, 0.4202, 0.3384,
          0.3621, 0.3469, 0.3579, 0.3799, 0.4008, 0.3806, 0.2410, 0.4138, 0.4040,
          0.4092, 0.3293, 0.3677, 0.3911, 0.3932, 0.3785, 0.3657, 0.4482, 0.3493,
          0.3923, 0.3686, 0.3903, 0.3796, 0.9301, 0.3713, 0.4322, 0.4238, 0.3864,
          0.3547, 0.3531, 0.3495, 0.4793, 0.4070, 0.3873, 0.3998, 0.4365]]),
 tensor([0.9301]),
 t

In [16]:
score = pred[0]
score.shape

torch.Size([1, 107])

Recall that there are `107` diff languages.

In [24]:
score[0, pred[2].item()].item() == pred[1].item()

True

Let's test with our own recorded sounds.

**Rmk.** Facebook audio record will save the file in MP4 format. The `load_audio()` method does not accept MP4, so one has to convert to, say, MP3. For example, one can use the `ffmpeg` command to do this
```bash
ffmpeg -i en.mp4 -vn -acodec libmp3lame -ac 2 -ab 160k -ar 48000 en.mp3
```
Cf. <https://askubuntu.com/questions/84584/converting-mp4-to-mp3>

In [34]:
from pathlib import Path
path_en = Path.home() / "downloads/en.mp3"
en = language_clf.load_audio(str(path_en))
language_clf.classify_batch(en)[1:]

(tensor([0.7831]), tensor([32]), ['gv'])

In [33]:
path_vn = Path.home() / "downloads/vn.mp3"
vn = language_clf.load_audio(str(path_vn))
language_clf.classify_batch(vn)[1:]

(tensor([0.8642]), tensor([102]), ['vi'])

In [32]:
path_twn = Path.home() / "downloads/twn.mp3"
twn = language_clf.load_audio(str(path_twn))
language_clf.classify_batch(twn)[1:]

(tensor([0.8148]), tensor([102]), ['vi'])

In [41]:
languages107 = [
    "Abkhazian",
    "Afrikaans",
    "Amharic",
    "Arabic",
    "Assamese",
    "Azerbaijani",
    "Bashkir",
    "Belarusian",
    "Bulgarian",
    "Bengali",
    "Tibetan",
    "Breton",
    "Bosnian",
    "Catalan",
    "Cebuano",
    "Czech",
    "Welsh",
    "Danish",
    "German",
    "Greek",
    "English",
    "Esperanto",
    "Spanish",
    "Estonian",
    "Basque",
    "Persian",
    "Finnish",
    "Faroese",
    "French",
    "Galician",
    "Guarani",
    "Gujarati",
    "Manx",
    "Hausa",
    "Hawaiian",
    "Hindi",
    "Croatian",
    "Haitian",
    "Hungarian",
    "Armenian",
    "Interlingua",
    "Indonesian",
    "Icelandic",
    "Italian",
    "Hebrew",
    "Japanese",
    "Javanese",
    "Georgian",
    "Kazakh",
    "Central Khmer",
    "Kannada",
    "Korean",
    "Latin",
    "Luxembourgish",
    "Lingala",
    "Lao",
    "Lithuanian",
    "Latvian",
    "Malagasy",
    "Maori",
    "Macedonian",
    "Malayalam",
    "Mongolian",
    "Marathi",
    "Malay",
    "Maltese",
    "Burmese",
    "Nepali",
    "Dutch",
    "Norwegian Nynorsk",
    "Norwegian",
    "Occitan",
    "Panjabi",
    "Polish",
    "Pushto",
    "Portuguese",
    "Romanian",
    "Russian",
    "Sanskrit",
    "Scots",
    "Sindhi",
    "Sinhala",
    "Slovak",
    "Slovenian",
    "Shona",
    "Somali",
    "Albanian",
    "Serbian",
    "Sundanese",
    "Swedish",
    "Swahili",
    "Tamil",
    "Telugu",
    "Tajik",
    "Thai",
    "Turkmen",
    "Tagalog",
    "Turkish",
    "Tatar",
    "Ukrainian",
    "Urdu",
    "Uzbek",
    "Vietnamese",
    "Waray",
    "Yiddish",
    "Yoruba",
    "Mandarin Chinese",
]
len(languages107)

107

In [42]:
languages107[30:34]

['Guarani', 'Gujarati', 'Manx', 'Hausa']